import {
  DEV_BACKEND_URL_API_KEY,
  DEV_BACKEND_URL_AUTH_DOMAIN,
  DEV_BACKEND_URL_PROJECT_ID,
  DEV_BACKEND_URL_STORAGE_BUCKET,
  DEV_BACKEND_URL_MESSAGING_SENDER_ID,
  DEV_BACKEND_URL_APP_ID,

  PROD_BACKEND_URL_API_KEY,
  PROD_BACKEND_URL_AUTH_DOMAIN,
  PROD_BACKEND_URL_PROJECT_ID,
  PROD_BACKEND_URL_STORAGE_BUCKET,
  PROD_BACKEND_URL_MESSAGING_SENDER_ID,
  PROD_BACKEND_URL_APP_ID,
} from '@env'

const devEnvironmentVariables = {
  DEV_BACKEND_URL_API_KEY,
  DEV_BACKEND_URL_AUTH_DOMAIN,
  DEV_BACKEND_URL_PROJECT_ID,
  DEV_BACKEND_URL_STORAGE_BUCKET,
  DEV_BACKEND_URL_MESSAGING_SENDER_ID,
  DEV_BACKEND_URL_APP_ID,
}

const prodEnvironmentVariables = {
  PROD_BACKEND_URL_API_KEY,
  PROD_BACKEND_URL_AUTH_DOMAIN,
  PROD_BACKEND_URL_PROJECT_ID,
  PROD_BACKEND_URL_STORAGE_BUCKET,
  PROD_BACKEND_URL_MESSAGING_SENDER_ID,
  PROD_BACKEND_URL_APP_ID,
}

export default __DEV__ ? devEnvironmentVariables : prodEnvironmentVariables;